version: '2'
services:
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306" #mariadb-port
    container_name: mariadb

  redis-cache:
    image: redis:alpine

    volumes:
      - ./redis-conf/redis_cache.conf:/etc/conf.d/redis.conf

    command: ["redis-server","/etc/conf.d/redis.conf"]

    container_name: redis-cache

  redis-queue:
    image: redis:alpine

    volumes:
      - ./redis-conf/redis_queue.conf:/etc/conf.d/redis.conf

    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-queue

  redis-socketio:
    image: redis:alpine

    volumes:
      - ./redis-conf/redis_socketio.conf:/etc/conf.d/redis.conf

    command: ["redis-server","/etc/conf.d/redis.conf"]

    container_name: redis-socketio

  frappe:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
    command: "bench serve --port 8000"
    image: hieueastagile/frappe-dev
    ports:
      - "8000:8000" #webserver_port
    stdin_open: true
    tty: true
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
      - frappe-socketio
      - frappe-watch
      - frappe-schedule
      - frappe-worker-short
      - frappe-worker-long
      - frappe-worker-default
    environment:
      DEV_SERVER: 1
    container_name: frappe

  frappe-socketio:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
    command: "/usr/bin/node apps/frappe/socketio.js"
    image: hieueastagile/frappe-dev
    ports:
      - "9000:9000" #socketio_port
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  frappe-watch:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
    command: "bench watch"
    image: hieueastagile/frappe-dev
    ports:
      - "6787:6787" #file_watcher_port
    tty: true
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  frappe-schedule:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
    command: "bench schedule"
    image: hieueastagile/frappe-dev
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  frappe-worker-short:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
    command: "bench worker --queue short"
    image: hieueastagile/frappe-dev
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  frappe-worker-long:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
    command: "bench worker --queue long"
    image: hieueastagile/frappe-dev
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  frappe-worker-default:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
    command: "bench worker --queue default"
    image: hieueastagile/frappe-dev
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
