version: '2'
services:
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306" #mariadb-port
    container_name: mariadb

  frappe:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
    command: "bench serve --port 8000"
    image: hieueastagile/frappe-dev
    ports:
      - "8000:8000" #webserver_port
    stdin_open: true
    tty: true
    links:
      - mariadb
    depends_on:
      - mariadb
    environment:
      DEV_SERVER: 1
    container_name: frappe
