#!/usr/bin/env bash
DOCKER_COMPOSE_UP_CONTAINER_NAME=frappe
DOCKER_COMPOSE_RUN_DEV_CONTAINER_NAME=frappedev
DOCKER_COMPOSE_UP_CONTAINER_RUNNING=$(docker inspect --format="{{.State.Running}}" $DOCKER_COMPOSE_UP_CONTAINER_NAME 2> /dev/null)
DOCKER_COMPOSE_RUN_DEV_CONTAINER_RUNNING=$(docker inspect --format="{{.State.Running}}" $DOCKER_COMPOSE_RUN_DEV_CONTAINER_NAME 2> /dev/null)

if [ "$DOCKER_COMPOSE_UP_CONTAINER_RUNNING" == "true" ]; then
  docker exec -it $DOCKER_COMPOSE_UP_CONTAINER_NAME bench $@
elif [ "$DOCKER_COMPOSE_RUN_DEV_CONTAINER_RUNNING" == "true" ]; then
  docker exec -it $DOCKER_COMPOSE_RUN_DEV_CONTAINER_NAME bench $@
else
  docker-compose run --rm frappe bench $@
fi
